version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      # vhost
      - ./nginx/test.conf:/etc/nginx/conf.d/test.conf
      # c칩digo
      - ../:/var/www
      # logs
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: ./php-fpm
    volumes:
      # c칩digo
      - ../:/var/www

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
    volumes:
      # Creaci칩n autom치tica de bd
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # Almacenamiento de la base de datos
      - ./mysql/data:/var/lib/mysql
